import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'

function Home() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.5 },
    },
  }

  return (
    <motion.div
      className="min-h-screen flex items-center justify-center px-4"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      <div className="max-w-4xl w-full">
        <motion.div variants={itemVariants} className="text-center mb-12">
          <h1 className="text-5xl md:text-6xl font-bold bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent mb-4">
            🎯 AI Treasure Hunt Creator
          </h1>
          <p className="text-xl text-gray-600 mb-6">
            Generate amazing treasure hunts with AI-powered clues
          </p>
        </motion.div>

        <motion.div
          variants={itemVariants}
          className="grid md:grid-cols-2 gap-6 mb-12"
        >
          <Link
            to="/create"
            className="card p-8 text-center hover:shadow-xl transition-all cursor-pointer transform hover:scale-105"
          >
            <div className="text-5xl mb-4">🎨</div>
            <h2 className="text-2xl font-bold mb-2">Create Hunt</h2>
            <p className="text-gray-600 mb-4">
              Design your own treasure hunt with AI-generated clues
            </p>
            <button className="btn-primary w-full">
              Start Creating
            </button>
          </Link>

          <Link
            to="/join"
            className="card p-8 text-center hover:shadow-xl transition-all cursor-pointer transform hover:scale-105"
          >
            <div className="text-5xl mb-4">🔍</div>
            <h2 className="text-2xl font-bold mb-2">Join Hunt</h2>
            <p className="text-gray-600 mb-4">
              Join an existing treasure hunt and compete for the top spot
            </p>
            <button className="btn-secondary w-full">
              Find Hunts
            </button>
          </Link>
        </motion.div>

        <motion.div variants={itemVariants} className="card p-8">
          <h3 className="text-2xl font-bold mb-4">Features</h3>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="flex items-start">
              <span className="text-2xl mr-3">✨</span>
              <div>
                <h4 className="font-bold">AI-Powered Clues</h4>
                <p className="text-gray-600 text-sm">Generated by Google Gemini</p>
              </div>
            </div>
            <div className="flex items-start">
              <span className="text-2xl mr-3">🎭</span>
              <div>
                <h4 className="font-bold">Multiple Themes</h4>
                <p className="text-gray-600 text-sm">Fun, Academic, Comics, Riddles & more</p>
              </div>
            </div>
            <div className="flex items-start">
              <span className="text-2xl mr-3">🏆</span>
              <div>
                <h4 className="font-bold">Leaderboards</h4>
                <p className="text-gray-600 text-sm">Real-time rankings & scores</p>
              </div>
            </div>
            <div className="flex items-start">
              <span className="text-2xl mr-3">📜</span>
              <div>
                <h4 className="font-bold">E-Certificates</h4>
                <p className="text-gray-600 text-sm">Instant digital certificates</p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  )
}

export default Home
